[build]
builder = "NIXPACKS"

[deploy]
runtime = "V2"
numReplicas = 1
startCommand = /bin/sh -c "uvicorn main:app --host 0.0.0.0 --port $PORT"
sleepApplication = false
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10